name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run-job:
        type: boolean
        required: false
        description: 'Run Specific Job'
      custom_message:
        description: 'Enter a custom message'
        required: true
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "${{ github.event.inputs.custom_message }}"
      - name: Printing run-job boolean value
        run: |
          if ${{ github.event.inputs.run_job }} == 'true'; then
            echo ${{ github.event.inputs.run_job }}
          fi
